version: "3"

services:
  db:
    image: postgres:14-alpine
    restart: always
    build:
      context: ./db_data
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db_data/init.sql:/docker-entrypoint-initdb.d/init.sql          
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    env_file: .env
    build:
      context : ./app
      dockerfile: Dockerfile
    #image: binardino/gaming_of_a_lifetime:latest
    restart: always
    ports:
      - "${STAPP_PORT}:${STAPP_PORT}"
