version: "3"

services:
  db:
    image : postgres
    environment:
      env_file: variables.env
    volumes:
      - db_data:/var/lib/postgres/data
    restart: always
    ports:
      - "5432:5432"

  app:
    depends_on:
      - db
    images: binardino/gaming_of_a_lifetime:latest
    restart: always
    ports:
      - "8501:8501"

volumes: db_data: {}