version: "3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      
    env_file: .env
    #environment:
      # env_file: dbcredentials.env
      #- POSTGRES_USER=${POSTGRES_USER}
      ##- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      #- POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_HOST=${POSTGRES_HOST}
      #- POSTGRES_PORT=${POSTGRES_PORT}
    build:
      context: .
      args:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_TABLE=${POSTGRES_TABLE}
#    volumes:
 #     - db_data_gaming:/var/lib/postgresql/data
  #    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  app:
    depends_on:
      - db
    build:
      context : ./app
      dockerfile: Dockerfile
    #image: binardino/gaming_of_a_lifetime:latest
    restart: always
    ports:
      - "${STAPP_PORT}:${STAPP_PORT}"

#volumes:
#  db_data_gaming: