-- CSV produced by import_hltb.py: 18 columns, no id (SERIAL, auto-generated by DB),
-- includes country_dev/studio/editor merged from gaming_lifetime.
-- Column order must match the CSV header exactly.
COPY public.how_long_to_beat
    (game_name, console, game_type, finished,
     published_year, played_year, hours_played, perso_score, multiplayed,
     comp_100, comp_all, comp_main, comp_plus,
     platform, developer,
     country_dev, studio, editor)
FROM '/docker-entrypoint-initdb.d/csv_file/hltb_scrap.csv'
DELIMITER ','
CSV HEADER;
