import pandas as pd
from sqlalchemy import create_engine
from db_import_utils import upsert_dataframe
import os

DB_URL = os.environ["DATABASE_URL"]
CSV_PATH = "db_data/csv/hltb_scrap.csv"

def main():
    engine = create_engine(DB_URL)
    df = pd.read_csv(CSV_PATH)

    df_gl = pd.read_sql(
        "SELECT game_name, country_dev, studio, editor FROM gaming_lifetime",
        engine,
    )
    df = df.merge(df_gl, on="game_name", how="left")
    df = df.drop(columns=["id"], errors="ignore")  # id is auto-generated by the DB

    upsert_dataframe(
        df=df,
        table="how_long_to_beat",
        engine=engine,
        conflict_cols=["game_name", "platform"],
    )

    df.to_csv(CSV_PATH, index=False)
    print(f"✅ {len(df)} rows processed")

if __name__ == "__main__":
    main()
